name: Slack Message Scheduler (Java)

on:
  schedule:
    - cron: '0 * * * *'  # 매시 0분마다 실행
  workflow_dispatch: # 수동 실행 가능

jobs:
  send_slack_message:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4 # v4 버전 사용 권장
      - name: Set up JDK 17
        uses: actions/setup-java@v4 # v4 버전 사용 권장
        with:
          java-version: '17'
          distribution: ' Temurin'
      - name: 실행 가능한 JAR 파일 빌드 (Maven 예시)
        run: mvn clean install # Maven 빌드 명령 (Gradle 사용하는 경우 gradlew build)
      - name: 자바 프로그램 실행 및 Slack 메시지 전송
        run: java -jar target/slack-webhook-sender-1.0-SNAPSHOT.jar # JAR 파일 실행 (파일명은 pom.xml 설정에 따라 다를 수 있음)
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }} # 환경변수로 Webhook URL 전달